### ISSUE TITLE
[Metamask] call contract createNewBallot() function 

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/dapp#51]
When user creates ballot it triggers a metamask transaction to create a ballot calling createNewBallot(). createNewBallot parameters are createNewBallot(address from, bytes32 ipfsTitle)
- [x] send json to IPFS to get hash
- [x] implement API call with web3.js and construct transaction
- [x] implement getter to get the transaction status
- [x] dedicated page for create ballot

The UI should show the state of the transaction.

**Comment by virgile-dev** [comment]
Transaction status
<img width="990" alt="capture d ecran 2018-04-22 a 13 53 26" src="https://user-images.githubusercontent.com/11473995/39094737-d2329af6-4634-11e8-9fdd-b79c068befd1.png">

**Comment by AlexJupiter** [comment]
A proposed change to the UX here, is that we have a dedicated "create ballot page" (so not a modal) and the transactions status will appear on that page after a user attempts to create a ballot.

Once the transaction is successful they will then be directed to the ballot, as the screenshot in the above comment shows.

**Comment by aecc** [comment]
I'm not sure about the UX terminology here, what's the difference between a page and a modal?

**Comment by AlexJupiter** [comment]
I define a page as a new screen, normally with its own specific route scope. So Sovereign.com/profile or Sovereign.com/home

A modal is a pop up. It can display similar content as a page, however it normally overlays content on the existing page. 

The current implementation of Create Ballot is a modal and I’m proposing we change it to a new page

**Comment by aecc** [comment]
I agree, however I think it should be possible to browse the rest of the pages while waiting for the transaction complete. What do you think?

**Comment by AlexJupiter** [comment]
>  I think it should be possible to browse the rest of the pages while waiting for the transaction complete.

I agree. Perhaps a notification section for pending transactions?

However, for v0.2 of the dApp, we are only going to have one page anyway, so perhaps not as important for now to consider.

**Comment by aecc** [comment]
> I agree. Perhaps a notification section for pending transactions?
That'd be nice. 

> However, for v0.2 of the dApp, we are only going to have one page anyway, so perhaps not as important for now to consider.
Exactly, let's keep that for a later iteration
