### ISSUE TITLE
Can't deploy sovereign locally

### ISSUE THREAD

**Issue by Troublor** [DemocracyEarth/dapp#516]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
When I deploy `sovereign` locally, following the instructions in `README.md`. After configuring `settings.json` and start `sovereign` using `meteor npm run start:dev`,  I can see in the console that `sovereign` is scanning ethereum mainnet for DAO events. But the webpage `localhost:3000` is totally a mess as shown in the screenshot. 
![Screenshot 2020-07-09 at 16 08 51](https://user-images.githubusercontent.com/14846504/87014279-7d85dc00-c1fe-11ea-9248-51d1176cf6c5.png)
* What did you expect should have happened?
Webpage should work as normal.
* What was the config you used?
`settings.json`
```json
{
  "galaxy.meteor.com": {
    "env": {
      "ROOT_URL": "http://localhost",
      "MONGO_URL": "",
      "MONGO_OPLOG_URL": "",
      "SPIDERABLE_FLAGS": ""
    }
  },
  "AWSAccessKeyId": "",
  "AWSSecretAccessKey": "",
  "private": {
    "API": {
      "facebook": {
        "appId": "",
        "appSecret": ""
      },
      "twitter": {
        "APIKey": "",
        "APISecret": ""
      },
      "amazon": {
        "AWSBucket": "",
        "AWSRegion": "",
        "AWSAcl": ""
      }
    },
    "sentryPrivateDSN": "",
    "smtpServer": "",
    "web3": {
      "config": "mainnet",
      "network": "https://mainnet.infura.io/v3/892a7c25469e4cdfaa080643d5073ba0",
      "secret": "MY_INFURA_APP_SECRET",
      "id": "MY_INFURA_APP_ID",
      "fortmatic": ""
    }
  },
  "public": {
    "AWSHostingURL": "",
    "sentryPublicDSN": "",
    "analyticsSettings": {
      "Google Analytics": {
        "trackingId": ""
      }
    },
    "app": {
      "name": "MolochDAO",
      "url": "https://molochdao.com",
      "language": "en",
      "logo": "images/moloch.png",
      "twitter": "MolochDAO",
      "bio": "Building Ethereum 2.0",
      "development": true,
      "config": {
        "blockchainLogin": false,
        "commentRanking": true,
        "proposalDrafting": true,
        "appCache": false,
        "mailNotifications": true,
        "token": {
          "defaultCode": "ETH"
        },
        "permissioned": {
          "active": false,
          "checkDomain": false,
          "checkList": true
        },
        "displayLanding": false,
        "allowWebVotes": true,
        "defaultRules": {
          "quadraticVoting": false,
          "balanceVoting": false,
          "pollVoting": false
        },
        "interface": {
          "showTransactions": true,
          "mainFeed": {
            "onlyParentPosts": true,
            "landingMaxItems": 5
          },
          "adminBallotCreatorOnly": {
            "active": false,
            "email": ""
          }
        },
        "governance": {
          "dictatorship": true,
          "censorship": true,
          "dictator": {
            "userId": "",
            "publicAddress": ""
          }
        },
        "profile": {
          "uploadAvatarToCloud": false,
          "nationalitySetting": false,
          "editableUsername": false,
          "notificationsEmail": false,
          "updatable": false
        },
        "loginOptions": {
          "blockstack": false,
          "metamask": true,
          "email": false,
          "blockchainLogin": false
        },
        "navbar": [
          {
            "selected": true,
            "label": "dao",
            "url": "https://moloch.democracy.earth"
          },
          {
            "selected": false,
            "label": "paper",
            "url": "https://github.com/MolochVentures/Whitepaper/blob/master/Whitepaper.pdf"
          },
          {
            "selected": false,
            "label": "code",
            "url": "https://github.com/MolochVentures/moloch"
          },
          {
            "selected": false,
            "label": "tweets",
            "url": "https://twitter.com/MolochDAO"
          }
        ]
      }
    },
    "web": {
      "sites": {
        "tokens": "https://molochdao.discourse.group/t/how-to-launch-a-dao/82",
        "blockExplorer": "https://etherscan.io"
      },
      "template": {
        "settings": "/templates/moloch/moloch.json"
      }
    },
    "web3": {
      "config": "mainnet",
      "network": "",
      "secret": "",
      "id": "",
      "fortmatic": ""
    }
  }
}
```
* What stacktrace or error message from your provider did you see?
![Screenshot 2020-07-09 at 16 10 34](https://user-images.githubusercontent.com/14846504/87014448-bfaf1d80-c1fe-11ea-8f13-ee060aa4c1a6.png)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by santisiri** [comment]
Have you tried with the latest version currently available on `master` ? 

We deprecated the use of Infura and are now working with Graph Protocol.

**Comment by Troublor** [comment]
@santisiri Yes, I have tried the latest version currently on `master`, I found the problem is about the template. 
The template path specified in `settings.json` [here](https://github.com/DemocracyEarth/sovereign/blob/master/config/development/settings.json#L143) actually does not exist. When I change the path to `/templates/daoverse/daoversese.json` problems solved. 

Is this a mistake putting a wrong template path here?

**Comment by santisiri** [comment]
Clearly we should definitely update the template route on the default settings, thanks for noticing that!

**Comment by Troublor** [comment]
@santisiri Another problem is that after the website is loaded, the `CONNECT WALLET` button on the top right is not working. I click it and nothing happens. No errors are shown in the console. 

<img width="1917" alt="Screenshot 2020-08-12 at 17 18 21" src="https://user-images.githubusercontent.com/14846504/89998232-d8a86400-dcbf-11ea-9246-efe1fe9a8a83.png">

Any reason for this?

**Comment by santisiri** [comment]
That might have to do with Web3 Modal. 

Btw, we just merged a new version of the Dapp, now outstripped from meteor/mongo that runs on plain react. You can find this last release on `master`
