### ISSUE TITLE
Bogue CSS ? The right blocks partially cover the middle blocks

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyEarth/dapp#531]
Installation with Debian Buster

**The site will be displayed but, with a CSS problem, the right blocks partially cover the middle blocks.**

sudo apt install git
sudo git clone https://github.com/DemocracyEarth/dapp.git
cd dapp

sudo apt-get install gcc g++ make
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

curl -sL https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_14.x > setup_14.x
chmod +x setup_14.x
sudo ./setup_14.x

node -v
v14.12.0

npm -v
6.14.8

sudo npm install
sudo npm start

http://localhost:3000/

The site will be displayed but, with a CSS problem, the right blocks partially cover the middle blocks.

Then how can I use Democracy earth?
I am cruelly lacking information

Source : https://wiki.visionduweb.fr/index.php?title=Installer_DemocracyOS#Installer_Democracy_Earth

**Comment by santisiri** [comment]
Apparently this is an issue with Firefox. We'll work on fixing ASAP.

**Comment by ZerooCool** [comment]
Thank you for this feedback, hoping that this problem will be resolved soon.

Once installed, I was confused by the interface.

How do I use Democracy Earth?
How to create a voting proposal?
Where can I find users who can support in real time?

**Comment by santisiri** [comment]
Firefox support has been fixed.
