### ISSUE TITLE
[Metamask] call delegate() function

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/dapp#58]
When user has chosen a delegate by clicking on the radio button and then click on the `delegate`button it should trigger a metamask transaction. delegate function parameters are: `delegate(address from, address representative)`
 - [x] implement API call with web3.js and construct transaction.

**Comment by virgile-dev** [comment]
Status of the transaction:
<img width="881" alt="capture d ecran 2018-04-22 a 15 12 26" src="https://user-images.githubusercontent.com/11473995/39095366-a447782c-463f-11e8-8771-484e2e87436f.png">

**Comment by aecc** [comment]
The transaction is already implemented. Missing is the transaction status and a better UX.

**Comment by AlexJupiter** [comment]
Related issue: https://github.com/DemocracyEarth/dapp/issues/90
