### ISSUE TITLE
[Metamask] call contract revoke() delegation function

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/dapp#60]
When user clicks on `revoke` button it should trigger a metamask transaction.
 - [x] implement API call with web3.js and construct transaction.

**Comment by aecc** [comment]
Implemented. Missing transaction status.

**Comment by AlexJupiter** [comment]
Closing this issue, to celebrate that this task has been done, and then going to open a new issue just related to the transaction statuses.

**Comment by AlexJupiter** [comment]
Related issue: https://github.com/DemocracyEarth/dapp/issues/90
