### ISSUE TITLE
Style ballot-dashboard page

### ISSUE THREAD

**Issue by AlexJupiter** [DemocracyEarth/dapp#68]
Parent #69

**Comment by aecc** [comment]
@AlexJupiter Is this doable for 0.2.0 or should we leave it for 0.2.1?

**Comment by AlexJupiter** [comment]
@aecc we have already deleted angular-material on the new ballot-dashboard page on the ballot-dashboard branch. This branch will be merged in this milestone.  

I'm going to update this issue to reflect we're just deleting angular-material on the ballot dashboard page.

**Comment by LucasIsasmendi** [comment]
We continue this task on issue #49
