### ISSUE TITLE
Consolidate ReadMe Files

### ISSUE THREAD

**Issue by AlexJupiter** [DemocracyEarth/dapp#77]
Tasks
- [x] move dApp-Ser-Exp/readme content to main readme
- [x] delete dApp-Ser-Exp/readme file
- ~~delete `src` folder~~
- ~~rename `dApp-Ser-Exp` to `src`~~
- [x] test that someone new can get the dapp working from just using the readme

**Comment by aecc** [comment]
Hey @AlexJupiter , yes, it should be In progress. I set the Label before, but I guess that doesn't affect anymore the project Columns. So do we sop using the labels? I'll do the required changes

**Comment by AlexJupiter** [comment]
@aecc yep, I think we can stop using the labels now we have the columns. And what still needs needs to be done in terms of completing this task? Can we create some checkboxes?

**Comment by aecc** [comment]
I think it's all done. Just waiting for @virgile-dev to agree on the channel we are gonna use. I just haven't done the PR.

**Comment by virgile-dev** [comment]
Yup sorry for the delay in answering.
In short, we have only one public channel for development it's #developers. 
Then we have a bunch of private ones:
- development-crew
- devmeets
- dev-roadmap
Which have been pretty inactive.

So here is what I suggest we do. 
- Let's rename the channel to "development" 
- Pin a welcome message 
  - that explains the purpose of the channel and how often we plan to communicate there and asking for people to present themselves detailing their tech stack
  - that explains what are the repos people can contribute too and the tech stack behind it
  - create a label for "good-first-issue" make a link towards the filtered list of issues attached to that label
   - put the link to the most recent development update

And let's put a message in all the private channels indicating that now on we'll be communicating on the #development channel.

What do you guys think? I'll send this to Sandra and Paula as well to get feedback.

**Comment by AlexJupiter** [comment]
@virgile-dev this sounds great to me! I was initially reluctant to this, but it might also be wise to move our conversations from Telegram to this new channel as well. Perhaps we could also implement the GitHub slack bot?

**Comment by virgile-dev** [comment]
The slackbot for Github could be a great idea. I'm affraid that it floods the channel though.

**Comment by AlexJupiter** [comment]
Yeah, the slackbot should be in another channel. I have found having it in it's own dedicated channel has worked in the past. It's just a good link between Slack and GitHub.

**Comment by aecc** [comment]
I like the idea, however I believe we should have separate development channels for Sovereign and for the Dapp. I don't want any of the projects to be flooded with information that doesn't concern each other at the moment.

**Comment by virgile-dev** [comment]
I was thinking of the #development channel more as a way to onboard new comers and share updates not so much as a day to day communication medium (this should be Github as much as possible by the way). @aecc I'm thinking that one channel for whole dev is good from a communication perspective.

**Comment by virgile-dev** [comment]
@santisiri @SFSandra what's your take on this ?

**Comment by medied** [comment]
>I think it's all done. Just waiting for @virgile-dev to agree on the channel we are gonna use. I just haven't done the PR.

@aecc assuming the branch you are working on is `77-consolidate-readmes`. I think we should go ahead with PR and not let channel decision slow it down. 

For example, we could remove the following README.md line for the time being and decide on Slack channel in our next sync: 

>Dapp development is discussed actively in the slack channel #dev-dapp in democracyearth.slack.com

Also what about the 'delete src folder' and 'rename dApp-Ser-Exp to src' tasks in this issue's initial comment? They make sense to me but am curious whether you think the same or not

**Comment by aecc** [comment]
I'll keep the #development channel meanwhile, given that it's already created.

> Also what about the 'delete src folder' and 'rename dApp-Ser-Exp to src' tasks in this issue's initial comment? They make sense to me but am curious whether you think the same or not

That's part of #66. I prefer to leave it there, given that @LucasIsasmendi is better suit than me on structuring folders in js projects

**Comment by aecc** [comment]
Ah, it's not created. The one it's created is #developers. I'll reference that one meanwhile

**Comment by medied** [comment]
Closed with #94
